### ISSUE TITLE
how to get payload?

### ISSUE THREAD

**Issue by starit** [lewangbtcc/anti-XSS#1]
I try to run the script and get the following Error
```
Error: No link filter file in lib/payload/linkfilter.dic
You should put your own filter file in lib/payload/
```

**Comment by lewangbtcc** [comment]
Sorry for that, since I'm not planning to open source the payloads, including script tags, xss payloads and source filters.
Actually you can add them yourself.
BTW, the performance of anti-XSS is depending on **your own dictionary files**.

**linkfilter.dic** stores characters which contained in what links don't wanna scan, you should divide them with "\n". An example is as follow:
> github
> google

**scripttag.dic**: 

> \<script|\</script>


**xsspayload.dic**:

> document.cookie()

Be careful about the pair of script tag which is divided by "|".
